### ISSUE TITLE
How to include the client secret?

### ISSUE THREAD

**Issue by 3r1k0n** [whoisjuan/ChromeAuth2#1]
We need a client secret for any oAuth client. 
The README suggests passing it in the code like any other parameter, however, this variable is secret for a reason.

How can this library get the required secret field while maintaining security by not distributing it to everyone who downloads the extension?

**Comment by whoisjuan** [comment]
@3r1k0n If you want to avoid leaking the client secret you are going to need something that retrieves the authorization token server side.

In practical terms, it means reimplementing this block of code in the `oauth2.js` file against a server you control. This can be an AWS Lambda Function or a Google Cloud Function: https://github.com/whoisjuan/ChromeAuth2/blob/05b5fa605568c9a9e13b50b4788f1e088155855f/oauth2.js#L45-L83

So instead of making a request directly to the endpoint that gives you back the authorization token, you can use a server to do that handshake and send you back the final clean auth token. Since the server is controlled exclusively by you, you can store the client's secret safely on that side of things.

It's a simple implementation that requires you to set up a server and an endpoint but it's the only way you're going to be able to protect the client's secret.

Other potential solutions are: 

1) Obfuscating the JS with something like this: https://obfuscator.io. While there's no guarantee that this couldn't be reversed by an attacker, the reality is that un-obfuscating the code will take a considerable effort. Most conventional attacks against simple products will likely be deterred by this.

2) Letting the client's secret leak. While this is generally bad advice, a client secret on its own has a limited amount of power. In oAuth, the role of the client secret is to authenticate the app that is requesting access to the app but an attacker will still need to control the credentials of a user for real harmful access to happen.

Again, I'm not recommending leaking the client secret, but if you do you're not exposing a major attack vector. You're simply exposing a piece of data that will allow someone to make authorization requests on behalf of your app but not on behalf of your users. I'm not suggesting this as an acceptable implementation but depending on what your app does, this could be something that doesn't represent a major issue.

Your users are still in control of the whole handshake because they will need to enter the credentials of the system they are authorizing against and that's a transaction between them and the third party they are authenticating against.

The major damage here is that someone could use the client secret to request a larger scope or reimplement your oAuth in another client without your knowledge, but the oAuth party that is receiving your client secret is still in control of the whole authorization process so the attack surface here is very limited.
